"""
Ligand Force Field Parameter Generation Workflow
=================================================
Provides tools to:

1. Parse Gaussian .log/.gjf files for the final optimised geometry.
2. Read RESP charges from antechamber MOL2 files or plain charge files.
3. Read LigParGen OPLS-AA Lennard-Jones parameters (.itp or .prm/.lj).
4. Perform unit conversions (kcal/mol → K, nm → Å).
5. Validate atom-count and charge-sum consistency.
6. Write an aligned parameter.txt output file.

Level of theory assumed for RESP fitting: HF/6-31G* (standard AMBER protocol).
ESP grid generated by Gaussian (IOp(6/33=2) keyword), two-stage RESP fitting
via ``antechamber -c resp``.

Unit conversion formulas
------------------------
  epsilon (kcal/mol) → K : epsilon_K  = epsilon_kcal  * 503.22
  sigma   (nm)       → Å : sigma_Ang  = sigma_nm       * 10.0
  epsilon (kJ/mol)   → K : epsilon_K  = epsilon_kJ     * 120.272

References
----------
  Cornell et al.  JACS 117, 5179 (1995)  – AMBER RESP protocol
  Jorgensen et al. JACS 118, 11225 (1996) – OPLS-AA
  Dodda et al.    Nucleic Acids Res. 45, W331 (2017) – LigParGen

Software versions (recommended)
--------------------------------
  Gaussian 16 Rev. C.01
  AmberTools >= 22
  LigParGen   web server (http://zarbi.chem.yale.edu/ligpargen/)

"""

import os
import re
import warnings
from typing import Dict, List, Optional

# ---------------------------------------------------------------------------
# Unit conversion constants
# ---------------------------------------------------------------------------
KCAL_MOL_TO_K = 503.22   # 1 kcal/mol = 503.22 K
KJ_MOL_TO_K = 120.272     # 1 kJ/mol  = 120.272 K
ANGSTROM_PER_NM = 10.0    # 1 nm = 10 Å

# Maximum allowed deviation of the total charge sum from an integer value
CHARGE_DEVIATION_THRESHOLD = 0.01  # e

# Placeholder string for missing LJ parameters in the output table
_LJ_NOT_AVAILABLE = "N/A"

# Atomic number → element symbol lookup (covers common organic / drug-like atoms)
_ATOMIC_SYMBOLS: Dict[int, str] = {
    1: "H",  2: "He",  3: "Li",  4: "Be",  5: "B",
    6: "C",  7: "N",   8: "O",   9: "F",  10: "Ne",
    11: "Na", 12: "Mg", 13: "Al", 14: "Si", 15: "P",
    16: "S",  17: "Cl", 18: "Ar", 19: "K",  20: "Ca",
    26: "Fe", 27: "Co", 28: "Ni", 29: "Cu", 30: "Zn",
    35: "Br", 53: "I",
}


# ---------------------------------------------------------------------------
# Custom exceptions
# ---------------------------------------------------------------------------

class LigandParameterError(Exception):
    """Base exception for ligand-parameter errors."""


class GeometryExtractionError(LigandParameterError):
    """Raised when no valid geometry block can be found."""


class ChargeReadError(LigandParameterError):
    """Raised when RESP charges cannot be parsed."""


class LJParameterError(LigandParameterError):
    """Raised when Lennard-Jones parameters cannot be parsed."""


# ---------------------------------------------------------------------------
# Geometry parsers
# ---------------------------------------------------------------------------

def parse_gaussian_log(filepath: str) -> List[Dict]:
    """Extract the final optimised geometry from a Gaussian .log file.

    The function reads every ``Standard orientation:`` block and returns
    the *last* one (i.e. the converged structure).  Coordinates are in Å.

    Parameters
    ----------
    filepath:
        Path to a Gaussian output file (.log or .out).

    Returns
    -------
    list of dict
        Each dict has keys ``atom_id`` (int), ``element`` (str),
        ``x``, ``y``, ``z`` (float, Å).

    Raises
    ------
    FileNotFoundError
        If *filepath* does not exist.
    GeometryExtractionError
        If no ``Standard orientation:`` block is found.
    """
    if not os.path.isfile(filepath):
        raise FileNotFoundError(f"Gaussian log file not found: {filepath}")

    current_block: List[Dict] = []
    last_good_block: List[Dict] = []
    in_orient = False
    skip_lines = 0

    with open(filepath, "r") as fh:
        for line in fh:
            stripped = line.strip()

            if "Standard orientation:" in line:
                in_orient = True
                skip_lines = 4  # dashes + header + dashes + one blank
                current_block = []
                continue

            if in_orient:
                if skip_lines > 0:
                    skip_lines -= 1
                    continue

                if re.match(r"^\s*-+\s*$", line):
                    # End of the orientation block
                    last_good_block = current_block[:]
                    in_orient = False
                    continue

                parts = stripped.split()
                if len(parts) >= 6:
                    try:
                        atom_num = int(parts[0])
                        atomic_num = int(parts[1])
                        x = float(parts[3])
                        y = float(parts[4])
                        z = float(parts[5])
                        element = _ATOMIC_SYMBOLS.get(atomic_num,
                                                       f"X{atomic_num}")
                        current_block.append({
                            "atom_id": atom_num,
                            "element": element,
                            "x": x,
                            "y": y,
                            "z": z,
                        })
                    except (ValueError, IndexError):
                        pass

    if not last_good_block:
        raise GeometryExtractionError(
            f"No 'Standard orientation' block found in '{filepath}'. "
            "Ensure the file is a valid Gaussian geometry-optimisation output."
        )

    return last_good_block


def parse_gaussian_gjf(filepath: str) -> List[Dict]:
    """Extract the input geometry from a Gaussian .gjf/.com file.

    Reads the first molecular-coordinate block (after the charge/multiplicity
    line).  Coordinates are assumed to be in Å (the Gaussian default).

    Parameters
    ----------
    filepath:
        Path to a Gaussian input file (.gjf or .com).

    Returns
    -------
    list of dict
        Same structure as :func:`parse_gaussian_log`.

    Raises
    ------
    FileNotFoundError
        If *filepath* does not exist.
    GeometryExtractionError
        If no coordinate block is found.
    """
    if not os.path.isfile(filepath):
        raise FileNotFoundError(f"Gaussian gjf file not found: {filepath}")

    atoms: List[Dict] = []
    blank_count = 0
    skipped_charge_spin = False
    in_coords = False
    atom_id = 1

    with open(filepath, "r") as fh:
        for line in fh:
            stripped = line.strip()

            if not stripped:
                blank_count += 1
                if in_coords:
                    break  # end of coordinate block
                continue

            # After 2 blank lines the next non-blank line is charge/multiplicity
            if blank_count >= 2 and not skipped_charge_spin:
                skipped_charge_spin = True
                in_coords = True
                continue  # skip the charge/multiplicity line itself

            if in_coords:
                parts = stripped.split()
                if len(parts) >= 4:
                    try:
                        element = parts[0]
                        x = float(parts[1])
                        y = float(parts[2])
                        z = float(parts[3])
                        atoms.append({
                            "atom_id": atom_id,
                            "element": element,
                            "x": x,
                            "y": y,
                            "z": z,
                        })
                        atom_id += 1
                    except ValueError:
                        pass

    if not atoms:
        raise GeometryExtractionError(
            f"No coordinate block found in '{filepath}'. "
            "Ensure this is a valid Gaussian input file."
        )

    return atoms


def parse_geometry(filepath: str) -> List[Dict]:
    """Auto-detect file type and extract geometry.

    Dispatches to :func:`parse_gaussian_log` for ``.log``/``.out`` files and
    to :func:`parse_gaussian_gjf` for ``.gjf``/``.com`` files.  For other
    extensions it tries the log parser first, then the gjf parser.

    Parameters
    ----------
    filepath:
        Path to any Gaussian file.

    Returns
    -------
    list of dict
        Atom list with keys ``atom_id``, ``element``, ``x``, ``y``, ``z``.
    """
    ext = os.path.splitext(filepath)[1].lower()
    if ext in (".log", ".out"):
        return parse_gaussian_log(filepath)
    if ext in (".gjf", ".com"):
        return parse_gaussian_gjf(filepath)
    # Unknown extension – try both
    try:
        return parse_gaussian_log(filepath)
    except GeometryExtractionError:
        return parse_gaussian_gjf(filepath)


# ---------------------------------------------------------------------------
# RESP charge reader
# ---------------------------------------------------------------------------

def read_resp_charges(filepath: str) -> List[float]:
    """Read RESP partial charges from a file.

    Supported formats
    -----------------
    * **MOL2** (``antechamber`` output): charge is column 9 inside the
      ``@<TRIPOS>ATOM`` section.
    * **Plain text**: one charge per line (or several charges per line);
      values that fall outside the range [-4, 4] are ignored.

    Parameters
    ----------
    filepath:
        Path to the charge file.

    Returns
    -------
    list of float
        RESP charges in atom-index order.

    Raises
    ------
    FileNotFoundError
        If *filepath* does not exist.
    ChargeReadError
        If no charges could be parsed.
    """
    if not os.path.isfile(filepath):
        raise FileNotFoundError(f"Charge file not found: {filepath}")

    ext = os.path.splitext(filepath)[1].lower()
    charges: List[float] = []

    if ext == ".mol2":
        in_atom_section = False
        with open(filepath, "r") as fh:
            for line in fh:
                stripped = line.strip()
                if stripped == "@<TRIPOS>ATOM":
                    in_atom_section = True
                    continue
                if stripped.startswith("@<TRIPOS>") and in_atom_section:
                    break
                if in_atom_section and stripped:
                    parts = stripped.split()
                    if len(parts) >= 9:
                        try:
                            charges.append(float(parts[8]))
                        except ValueError:
                            pass
    else:
        # Plain text or RESP output – extract float tokens in charge range
        with open(filepath, "r") as fh:
            for line in fh:
                stripped = line.strip()
                if not stripped or stripped.startswith("#"):
                    continue
                for token in stripped.split():
                    try:
                        val = float(token)
                        if -4.0 <= val <= 4.0:
                            charges.append(val)
                            break  # one charge per line
                    except ValueError:
                        pass

    if not charges:
        raise ChargeReadError(
            f"No RESP charges found in '{filepath}'. "
            "Provide an antechamber MOL2 file or a plain charge list."
        )

    return charges


# ---------------------------------------------------------------------------
# LigParGen / OPLS-AA LJ parameter reader
# ---------------------------------------------------------------------------

def read_ligpargen_parameters(filepath: str) -> Dict[str, Dict]:
    """Read OPLS-AA Lennard-Jones parameters from a LigParGen output file.

    Supported formats
    -----------------
    * **GROMACS .itp** (``[ atomtypes ]`` section):
        sigma in nm, epsilon in kJ/mol.
        Conversions: sigma_Å = sigma_nm × 10 ;  epsilon_K = epsilon_kJ × 120.272
    * **OPLS .prm / .lj** (column layout ``type  sigma(Å)  epsilon(kcal/mol)``):
        Conversion: epsilon_K = epsilon_kcal × 503.22

    Parameters
    ----------
    filepath:
        Path to the LigParGen output file.

    Returns
    -------
    dict
        ``{ atom_type: { 'sigma_ang': float, 'epsilon_K': float } }``

    Raises
    ------
    FileNotFoundError
        If *filepath* does not exist.
    LJParameterError
        If the format is unsupported or no parameters are found.
    """
    if not os.path.isfile(filepath):
        raise FileNotFoundError(
            f"LigParGen parameter file not found: {filepath}"
        )

    ext = os.path.splitext(filepath)[1].lower()
    params: Dict[str, Dict] = {}

    if ext == ".itp":
        in_atomtypes = False
        with open(filepath, "r") as fh:
            for line in fh:
                stripped = line.strip()
                if re.match(r"^\[\s*atomtypes\s*\]", stripped):
                    in_atomtypes = True
                    continue
                if stripped.startswith("[") and not re.match(
                    r"^\[\s*atomtypes\s*\]", stripped
                ):
                    in_atomtypes = False
                    continue
                if in_atomtypes and stripped and not stripped.startswith(";"):
                    parts = stripped.split()
                    # GROMACS ITP atomtypes layout:
                    #   name  at.num  mass  charge  ptype  sigma(nm)  epsilon(kJ/mol)
                    # 7 columns (indices 0-6); sigma at [5], epsilon at [6]
                    if len(parts) >= 7:
                        try:
                            atom_type = parts[0]
                            sigma_nm = float(parts[5])
                            epsilon_kj = float(parts[6])
                            params[atom_type] = {
                                "sigma_ang": sigma_nm * ANGSTROM_PER_NM,
                                "epsilon_K": epsilon_kj * KJ_MOL_TO_K,
                            }
                        except ValueError:
                            pass

    elif ext in (".prm", ".lj"):
        with open(filepath, "r") as fh:
            for line in fh:
                stripped = line.strip()
                if not stripped or stripped.startswith("!") \
                        or stripped.startswith("#"):
                    continue
                parts = stripped.split()
                if len(parts) >= 3:
                    try:
                        atom_type = parts[0]
                        sigma_ang = float(parts[1])      # already in Å
                        epsilon_kcal = float(parts[2])   # kcal/mol
                        params[atom_type] = {
                            "sigma_ang": sigma_ang,
                            "epsilon_K": epsilon_kcal * KCAL_MOL_TO_K,
                        }
                    except ValueError:
                        pass

    else:
        raise LJParameterError(
            f"Unsupported LigParGen file format '{ext}'. "
            "Supported: .itp (GROMACS), .prm / .lj (OPLS-AA)."
        )

    if not params:
        raise LJParameterError(
            f"No Lennard-Jones parameters found in '{filepath}'."
        )

    return params


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_parameters(
    atoms: List[Dict],
    charges: List[float],
    atom_types: Optional[List[str]] = None,
) -> None:
    """Check atom-count and charge-sum consistency.

    Parameters
    ----------
    atoms:
        Atom list from :func:`parse_geometry`.
    charges:
        RESP charges from :func:`read_resp_charges`.
    atom_types:
        Optional per-atom type labels (must have the same length as *atoms*).

    Raises
    ------
    LigandParameterError
        If a critical mismatch is detected.

    Warns
    -----
    UserWarning
        If the total charge sum deviates more than 0.01 e from an integer.
    """
    n_atoms = len(atoms)
    n_charges = len(charges)

    if n_atoms != n_charges:
        raise LigandParameterError(
            f"Atom/charge count mismatch: geometry has {n_atoms} atoms "
            f"but charge file has {n_charges} charges."
        )

    if atom_types is not None and len(atom_types) != n_atoms:
        raise LigandParameterError(
            f"Atom-type list has {len(atom_types)} entries "
            f"but there are {n_atoms} atoms."
        )

    charge_sum = sum(charges)
    nearest_int = round(charge_sum)
    if abs(charge_sum - nearest_int) > CHARGE_DEVIATION_THRESHOLD:
        warnings.warn(
            f"Total RESP charge sum is {charge_sum:.6f} e "
            f"(nearest integer: {nearest_int}). "
            f"Deviation > {CHARGE_DEVIATION_THRESHOLD} e – verify RESP convergence.",
            UserWarning,
            stacklevel=2,
        )
    else:
        print(
            f"[OK] Charge sum = {charge_sum:.6f} e  "
            f"(nearest integer: {nearest_int}, deviation "
            f"{abs(charge_sum - nearest_int):.6f} e)"
        )

    print(f"[OK] Atom count consistent: {n_atoms} atoms")


# ---------------------------------------------------------------------------
# Output writer
# ---------------------------------------------------------------------------

def write_parameter_file(
    atoms: List[Dict],
    charges: List[float],
    lj_params: Optional[Dict[str, Dict]] = None,
    atom_types: Optional[List[str]] = None,
    output_path: str = "parameter.txt",
) -> None:
    """Write the aligned ``parameter.txt`` file.

    Column layout (fixed-width, no overlap)
    ----------------------------------------
    AtomID | Type | Charge(e) | X(Ang) | Y(Ang) | Z(Ang) | Sigma(Ang) | Epsilon(K)

    Parameters
    ----------
    atoms:
        Atom list from :func:`parse_geometry`.
    charges:
        RESP charges (same length as *atoms*).
    lj_params:
        Optional dict from :func:`read_ligpargen_parameters`.
    atom_types:
        Optional per-atom type labels.  If *None*, element symbols are used.
    output_path:
        Destination path (default ``parameter.txt``).
    """
    validate_parameters(atoms, charges, atom_types)

    col_widths = {
        "atom_id":   6,
        "type":      8,
        "charge":   10,
        "x":        10,
        "y":        10,
        "z":        10,
        "sigma":    10,
        "epsilon":  10,
    }

    header = (
        f"{'AtomID':>{col_widths['atom_id']}}  "
        f"{'Type':<{col_widths['type']}}  "
        f"{'Charge(e)':>{col_widths['charge']}}  "
        f"{'X(Ang)':>{col_widths['x']}}  "
        f"{'Y(Ang)':>{col_widths['y']}}  "
        f"{'Z(Ang)':>{col_widths['z']}}  "
        f"{'Sigma(Ang)':>{col_widths['sigma']}}  "
        f"{'Epsilon(K)':>{col_widths['epsilon']}}"
    )
    separator = "-" * len(header)

    output_lines = [header, separator]

    for i, atom in enumerate(atoms):
        charge = charges[i]
        atom_type = (
            atom_types[i] if atom_types else atom.get("element", "UNK")
        )

        sigma_str = f"{_LJ_NOT_AVAILABLE:>{col_widths['sigma']}}"
        epsilon_str = f"{_LJ_NOT_AVAILABLE:>{col_widths['epsilon']}}"

        if lj_params is not None:
            if atom_type in lj_params:
                sigma_str = (
                    f"{lj_params[atom_type]['sigma_ang']:>{col_widths['sigma']}.4f}"
                )
                epsilon_str = (
                    f"{lj_params[atom_type]['epsilon_K']:>{col_widths['epsilon']}.4f}"
                )
            else:
                warnings.warn(
                    f"Atom type '{atom_type}' (atom {atom['atom_id']}) "
                    "not found in LJ parameter table.",
                    UserWarning,
                    stacklevel=2,
                )

        line = (
            f"{atom['atom_id']:>{col_widths['atom_id']}}  "
            f"{atom_type:<{col_widths['type']}}  "
            f"{charge:>{col_widths['charge']}.6f}  "
            f"{atom['x']:>{col_widths['x']}.4f}  "
            f"{atom['y']:>{col_widths['y']}.4f}  "
            f"{atom['z']:>{col_widths['z']}.4f}  "
            f"{sigma_str}  "
            f"{epsilon_str}"
        )
        output_lines.append(line)

    content = "\n".join(output_lines) + "\n"

    with open(output_path, "w") as fh:
        fh.write(content)

    print(f"[OK] Parameter file written to '{output_path}' ({len(atoms)} atoms)")


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------

def generate_parameters(
    gaussian_file: str,
    charge_file: str,
    ligpargen_file: Optional[str] = None,
    atom_types: Optional[List[str]] = None,
    output_path: str = "parameter.txt",
) -> str:
    """Full workflow: geometry → charges → LJ parameters → parameter.txt.

    Workflow steps
    --------------
    1. Parse optimised geometry from *gaussian_file* (Gaussian .log or .gjf).
    2. Read RESP charges from *charge_file* (antechamber MOL2 or plain text).
    3. Optionally read OPLS-AA LJ parameters from *ligpargen_file*.
    4. Validate atom-count and charge-sum consistency.
    5. Write the aligned ``parameter.txt``.

    Parameters
    ----------
    gaussian_file:
        Path to the Gaussian output (.log) or input (.gjf) file.
    charge_file:
        Path to the RESP charge file (antechamber .mol2 or plain text).
    ligpargen_file:
        Optional path to LigParGen output (.itp or .prm).
    atom_types:
        Optional per-atom type labels (same length as atoms).
        When *None* and *lj_params* is provided, element symbols are used
        as type keys (which must match keys in *lj_params*).
    output_path:
        Destination path for ``parameter.txt`` (default ``"parameter.txt"``).

    Returns
    -------
    str
        Absolute path to the written parameter file.

    Raises
    ------
    LigandParameterError
        On any critical failure (geometry extraction, charge reading,
        atom/charge count mismatch, etc.).
    FileNotFoundError
        If any input file does not exist.
    """
    print(f"[STEP 1] Parsing geometry from: {gaussian_file}")
    atoms = parse_geometry(gaussian_file)
    print(f"         → {len(atoms)} atoms extracted")

    print(f"[STEP 2] Reading RESP charges from: {charge_file}")
    charges = read_resp_charges(charge_file)
    print(f"         → {len(charges)} charges read")

    lj_params: Optional[Dict[str, Dict]] = None
    if ligpargen_file:
        print(f"[STEP 3] Reading LigParGen LJ parameters from: {ligpargen_file}")
        lj_params = read_ligpargen_parameters(ligpargen_file)
        print(f"         → {len(lj_params)} atom types loaded")

    print("[STEP 4] Validating consistency …")
    validate_parameters(atoms, charges, atom_types)

    print(f"[STEP 5] Writing parameter file to: {output_path}")
    write_parameter_file(
        atoms=atoms,
        charges=charges,
        lj_params=lj_params,
        atom_types=atom_types,
        output_path=output_path,
    )

    return os.path.abspath(output_path)
